package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.Project
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        add {
            feature {
                type = "CloudImage"
                id = "PROJECT_EXT_3"
                param("spotVm", "false")
                param("imageId", "jetbrains/teamcity-agent:latest-windowsservercore")
                param("memory", "4")
                param("spotPrice", "1")
                param("numberCores", "2")
                param("groupId", "TCAgentTrialResourceGroup")
                param("agent_pool_id", "-2")
                param("customEnvironmentVariables", "")
                param("enableSpotPrice", "false")
                param("storageAccount", "tctrialstorage")
                param("vmUsername", "")
                param("reuseVm", "false")
                param("source-id", "tc-agent")
                param("deployTarget", "SpecificGroup")
                param("vmPublicIp", "false")
                param("profileId", "arm-2")
                param("imageUrl", "")
                param("osType", "Linux")
                param("enableAcceleratedNetworking", "false")
                param("maxInstances", "1")
                param("region", "switzerlandnorth")
                param("imageType", "Container")
            }
        }
        add {
            feature {
                type = "CloudProfile"
                id = "arm-2"
                param("clientId", "0c2be730-4705-41b9-8c15-0ce5959b7152")
                param("secure:clientSecret", "credentialsJSON:7d53fca1-dce1-4a0d-8ccc-3a065fd83b19")
                param("profileServerUrl", "")
                param("system.cloud.profile_id", "arm-2")
                param("agent_pool_id", "-2")
                param("total-work-time", "10")
                param("credentialsType", "service")
                param("description", "")
                param("cloud-code", "arm")
                param("enabled", "true")
                param("environment", "AZURE")
                param("profileId", "arm-2")
                param("name", "Azure Agents")
                param("tenantId", "de9dd080-6e04-4524-9010-e747ec897e4b")
                param("next-hour", "")
                param("subscriptionId", "5e4e5d46-5476-4497-9f78-2a474e8e52ee")
                param("terminate-idle-time", "15")
                param("secure:passwords_data", "credentialsJSON:1af99ec0-0cf7-4d3a-857d-ee574e58aec2")
            }
        }
    }
}
